package a1.entity;

//Generated 28.04.2015 1:36:56 by Hibernate Tools 4.3.1

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;

import a1.annotations.Forms;
import a1.annotations.Synonym;




/**
* Contact generated by hbm2java
*/
@Entity
@Table(name="contact_status")
@Synonym(text="Статусы",textEng="Statuses")
@Forms(element="")
public class Contact_Status implements java.io.Serializable {
	@Synonym(text="Код",textEng="Code") 
	private int id;
    @Synonym(text="Наименование",textEng="Name")
    private String name;
    
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)    
    @Column(name = "id")         
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String toString(){
		return name;
	}
}